export const businesses = [
  {
    id: 1,
    name: "Nima Restaurant & Lounge Bar",
    type: "business",
    category: "Restaurant",
    breadcrumb: "Restaurants > Cyprus Restaurants > Kyrenia Restaurants > Nima Restaurant & Lounge Bar",
    rating: 5.0,
    reviews: 949,
    contact: {
      website: "http://nimacyprus.com",
      phone: "1232820897",
      email: "nimacyprus@lounge.com",
      hours: "10:00 - 00:00",
      status: "Closed",
    },
    about: `Nima Garden is a refined garden restaurant located in the heart of the historic Kyrenia Harbour...`,
    location: "Canbulat Cad. No: 37, Kyrenia 99300 Cyprus",
    country: "Cyprus",
    city: "Kyrenia",
    areaType: "Seaside",
    ambiance: "Calm",
    petFriendly: true,
    kidFriendly: true,
    workingHours: [
      { day: "Mon", hours: "10:00 AM - 23:00 PM" },
      { day: "Tue", hours: "10:00 AM - 23:00 PM" },
      { day: "Wed", hours: "10:00 AM - 23:00 PM" },
      { day: "Thu", hours: "10:00 AM - 23:00 PM" },
      { day: "Fri", hours: "10:00 AM - 02:00 AM" },
      { day: "Sat", hours: "10:00 AM - 02:00 AM" },
      { day: "Sun", hours: "10:00 AM - 23:00 PM" },
    ],
    photos: ["/hero1.png", "/hero2.png", "/hero3.png"], 
    mapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d0", 
  },
  {
    id: 2,
    name: "XXX Restaurant & Lounge Bar",
    type: "business",
    category: "Restaurant",
    breadcrumb: "Restaurants > Cyprus Restaurants > Kyrenia Restaurants > XXX Restaurant & Lounge Bar",
    rating: 4.5,
    reviews: 872,
    contact: {
      website: "http://xxxcyprus.com",
      phone: "1232820898",
      email: "xxxcyprus@lounge.com",
      hours: "10:00 - 00:00",
      status: "Open",
    },
    about: `XXX Restaurant offers a variety of Mediterranean and international dishes, perfect for family dining...`,
    location: "Canbulat Cad. No: 50, Kyrenia 99300 Cyprus",
    country: "Cyprus",
    city: "Kyrenia",
    areaType: "City Centre",
    ambiance: "Lively",
    petFriendly: false,
    kidFriendly: true,
    workingHours: [
      { day: "Mon", hours: "10:00 AM - 23:00 PM" },
      { day: "Tue", hours: "10:00 AM - 23:00 PM" },
      { day: "Wed", hours: "10:00 AM - 23:00 PM" },
      { day: "Thu", hours: "10:00 AM - 23:00 PM" },
      { day: "Fri", hours: "10:00 AM - 02:00 AM" },
      { day: "Sat", hours: "10:00 AM - 02:00 AM" },
      { day: "Sun", hours: "10:00 AM - 23:00 PM" },
    ],
    photos: ["/hero1.png", "/hero2.png", "/hero3.png"], 
    mapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d0", 
  },
  {
    id: 3,
    name: "Luna Coffee House",
    type: "business",
    category: "Cafe",
    breadcrumb: "Cafes > Cyprus Cafes > Kyrenia Cafes > Luna Coffee House",
    rating: 4.7,
    reviews: 134,
    contact: {
      website: "http://lunacyprus.com",
      phone: "1232820899",
      email: "luna@coffee.com",
      hours: "08:00 - 20:00",
      status: "Open",
    },
    about: `Luna Coffee House is the perfect spot for a relaxing break with specialty coffee and pastries...`,
    location: "Deniz Street, Kyrenia 99300 Cyprus",
    country: "Cyprus",
    city: "Kyrenia",
    areaType: "Seaside",
    ambiance: "Calm",
    petFriendly: true,
    kidFriendly: false,
    workingHours: [
      { day: "Mon", hours: "08:00 AM - 08:00 PM" },
      { day: "Tue", hours: "08:00 AM - 08:00 PM" },
      { day: "Wed", hours: "08:00 AM - 08:00 PM" },
      { day: "Thu", hours: "08:00 AM - 08:00 PM" },
      { day: "Fri", hours: "08:00 AM - 08:00 PM" },
      { day: "Sat", hours: "08:00 AM - 08:00 PM" },
      { day: "Sun", hours: "08:00 AM - 08:00 PM" },
    ],
    photos: ["/hero1.png", "/hero2.png", "/hero3.png"], 
    mapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d0", 
  },
  {
    id: 4,
    name: "Sunny Beach Resort",
    type: "business",
    category: "Hotel",
    breadcrumb: "Hotels > Cyprus Hotels > Kyrenia Hotels > Sunny Beach Resort",
    rating: 4.8,
    reviews: 482,
    contact: {
      website: "http://sunnybeachresort.com",
      phone: "1232820900",
      email: "contact@sunnybeachresort.com",
      hours: "24/7",
      status: "Open",
    },
    about: `Enjoy a luxurious stay at Sunny Beach Resort with beautiful views, great amenities, and endless activities...`,
    location: "Beachfront Street, Kyrenia 99300 Cyprus",
    country: "Cyprus",
    city: "Kyrenia",
    areaType: "Seaside",
    ambiance: "Calm",
    petFriendly: true,
    kidFriendly: true,
    workingHours: [
      { day: "Mon", hours: "24/7" },
      { day: "Tue", hours: "24/7" },
      { day: "Wed", hours: "24/7" },
      { day: "Thu", hours: "24/7" },
      { day: "Fri", hours: "24/7" },
      { day: "Sat", hours: "24/7" },
      { day: "Sun", hours: "24/7" },
    ],
    photos: ["/hero1.png", "/hero2.png", "/hero3.png"], 
    mapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d0", 
  },  {
    id: 5,
    name: "Sea Breeze Café",
    type: "business",
    category: "Cafe",
    breadcrumb: "Cafes > Cyprus Cafes > Kyrenia Cafes > Sea Breeze Café",
    rating: 4.6,
    reviews: 234,
    contact: {
      website: "http://seabreezecyprus.com",
      phone: "1232820901",
      email: "seabreeze@cafe.com",
      hours: "09:00 - 22:00",
      status: "Open",
    },
    about: `A cozy spot by the sea, Sea Breeze Café offers a variety of beverages and light bites with an amazing view.`,
    location: "Harbour Road, Kyrenia 99300 Cyprus",
    country: "Cyprus",
    city: "Kyrenia",
    areaType: "Seaside",
    ambiance: "Relaxed",
    petFriendly: true,
    kidFriendly: true,
    workingHours: [
      { day: "Mon", hours: "09:00 AM - 10:00 PM" },
      { day: "Tue", hours: "09:00 AM - 10:00 PM" },
      { day: "Wed", hours: "09:00 AM - 10:00 PM" },
      { day: "Thu", hours: "09:00 AM - 10:00 PM" },
      { day: "Fri", hours: "09:00 AM - 10:00 PM" },
      { day: "Sat", hours: "09:00 AM - 10:00 PM" },
      { day: "Sun", hours: "09:00 AM - 10:00 PM" },
    ],
    photos: ["/hero1.png", "/hero2.png", "/hero3.png"], 
    mapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d0", 
  },
  {
    id: 6,
    name: "Grandview Hotel",
    type: "business",
    category: "Hotel",
    breadcrumb: "Hotels > Cyprus Hotels > Kyrenia Hotels > Grandview Hotel",
    rating: 4.4,
    reviews: 312,
    contact: {
      website: "http://grandviewhotelcyprus.com",
      phone: "1232820902",
      email: "info@grandviewhotel.com",
      hours: "24/7",
      status: "Open",
    },
    about: `Stay at Grandview Hotel and enjoy panoramic views of Kyrenia's stunning coastline and luxury amenities.`,
    location: "Mountain Road, Kyrenia 99300 Cyprus",
    country: "Cyprus",
    city: "Kyrenia",
    areaType: "Seaside",
    ambiance: "Luxury",
    petFriendly: false,
    kidFriendly: true,
    workingHours: [
      { day: "Mon", hours: "24/7" },
      { day: "Tue", hours: "24/7" },
      { day: "Wed", hours: "24/7" },
      { day: "Thu", hours: "24/7" },
      { day: "Fri", hours: "24/7" },
      { day: "Sat", hours: "24/7" },
      { day: "Sun", hours: "24/7" },
    ],
    photos: ["/hero1.png", "/hero2.png", "/hero3.png"], 
    mapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d0", 
  },
  {
    id: 7,
    name: "Sunset Grill",
    type: "business",
    category: "Restaurant",
    breadcrumb: "Restaurants > Cyprus Restaurants > Kyrenia Restaurants > Sunset Grill",
    rating: 4.7,
    reviews: 540,
    contact: {
      website: "http://sunsetgrillcyprus.com",
      phone: "1232820903",
      email: "sunset@grill.com",
      hours: "11:00 - 23:00",
      status: "Open",
    },
    about: `A perfect dining experience by the beach offering grilled specialties with a beautiful sunset view.`,
    location: "Beach Road, Kyrenia 99300 Cyprus",
    country: "Cyprus",
    city: "Kyrenia",
    areaType: "Seaside",
    ambiance: "Charming",
    petFriendly: true,
    kidFriendly: true,
    workingHours: [
      { day: "Mon", hours: "11:00 AM - 11:00 PM" },
      { day: "Tue", hours: "11:00 AM - 11:00 PM" },
      { day: "Wed", hours: "11:00 AM - 11:00 PM" },
      { day: "Thu", hours: "11:00 AM - 11:00 PM" },
      { day: "Fri", hours: "11:00 AM - 11:00 PM" },
      { day: "Sat", hours: "11:00 AM - 11:00 PM" },
      { day: "Sun", hours: "11:00 AM - 11:00 PM" },
    ],
    photos: ["/hero1.png", "/hero2.png", "/hero3.png"], 
    mapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d0", 
  },
  {
    id: 8,
    name: "Mountain Escape Resort",
    type: "business",
    category: "Hotel",
    breadcrumb: "Hotels > Cyprus Hotels > Kyrenia Hotels > Mountain Escape Resort",
    rating: 4.9,
    reviews: 652,
    contact: {
      website: "http://mountainescaperesort.com",
      phone: "1232820904",
      email: "info@mountainescape.com",
      hours: "24/7",
      status: "Open",
    },
    about: `Enjoy a peaceful retreat at Mountain Escape Resort, offering luxury rooms and breathtaking mountain views.`,
    location: "Mountain Heights, Kyrenia 99300 Cyprus",
    country: "Cyprus",
    city: "Kyrenia",
    areaType: "Mountain",
    ambiance: "Tranquil",
    petFriendly: true,
    kidFriendly: true,
    workingHours: [
      { day: "Mon", hours: "24/7" },
      { day: "Tue", hours: "24/7" },
      { day: "Wed", hours: "24/7" },
      { day: "Thu", hours: "24/7" },
      { day: "Fri", hours: "24/7" },
      { day: "Sat", hours: "24/7" },
      { day: "Sun", hours: "24/7" },
    ],
    photos: ["/hero1.png", "/hero2.png", "/hero3.png"], 
    mapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d0", 
  },
  {
    id: 9,
    name: "Coastal Breeze Bistro",
    type: "business",
    category: "Restaurant",
    breadcrumb: "Restaurants > Cyprus Restaurants > Kyrenia Restaurants > Coastal Breeze Bistro",
    rating: 4.3,
    reviews: 432,
    contact: {
      website: "http://coastalbreezebistro.com",
      phone: "1232820905",
      email: "contact@coastalbreeze.com",
      hours: "10:00 - 22:00",
      status: "Open",
    },
    about: `Coastal Breeze Bistro is a delightful spot offering fresh seafood and Mediterranean cuisine with stunning coastal views.`,
    location: "Coastal Avenue, Kyrenia 99300 Cyprus",
    country: "Cyprus",
    city: "Kyrenia",
    areaType: "Seaside",
    ambiance: "Casual",
    petFriendly: false,
    kidFriendly: true,
    workingHours: [
      { day: "Mon", hours: "10:00 AM - 10:00 PM" },
      { day: "Tue", hours: "10:00 AM - 10:00 PM" },
      { day: "Wed", hours: "10:00 AM - 10:00 PM" },
      { day: "Thu", hours: "10:00 AM - 10:00 PM" },
      { day: "Fri", hours: "10:00 AM - 10:00 PM" },
      { day: "Sat", hours: "10:00 AM - 10:00 PM" },
      { day: "Sun", hours: "10:00 AM - 10:00 PM" },
    ],
    photos: ["/hero1.png", "/hero2.png", "/hero3.png"], 
    mapLink: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d0", 
  },
  ];
  